### ISSUE TITLE
Kan noen valg tillegges en enkel/avansert modus?

### ISSUE THREAD

**Issue by mariusmandal** [UKMNorge/UKMmonstring#43]
Og kan modus auto-velges i starten basert på målgruppe-tall?
`Fordi du potensielt har mer enn x00 deltakere, bruker du nå den avanserte utgaven. Trykk her for å aktivere enkel modus`

Hvilke valg som kan flyttes ut av enkel modus er usikkert, og må kartlegges.

**Comment by mariusmandal** [comment]
@tomandreaskristensen etter hvert som du opplever valg du tenker "dette trenger vi ikke", kan du enten varsle meg, eller legge det til som en kommentar her.

**Comment by mariusmandal** [comment]
Avansert modus: velge påmeldingsfrist != 23:59. Kan det f.eks. være mulig at man får en select-liste hvis man trykker på tidspunktet? Skjult valg da, men likevel mulig å få til?

**Comment by tomandreaskristensen** [comment]
Overnevnte at man får valget om man aktivt trykker på tidspunktet er en god løsning! Du trykker kun der hvis du er interessert i å bytte pga. et spesifikt behov.

**Comment by mariusmandal** [comment]
Skjemaet er nå forenklet og videresendingen flyttet ut. Valg for påmeldingsfrist går inn som feature request
